import { Schema } from '../../amplify/data/resource';

type CertificationCreate = Omit<Schema['Certifications']['type'], 'id' | 'createdAt' | 'updatedAt'>;

export const certifications: CertificationCreate[] = [
  {
    title: 'AWS Certified Solutions Architect - Associate',
    issuer: 'Amazon Web Services',
    credentialId: 'AWS-SAA-12345',
    credentialUrl: 'https://www.credly.com/badges/12345',
    issueDate: '2024-01-15',
    expirationDate: '2027-01-15',
    photoKey: 'aws-saa.png',
    content: 'Validated ability to design and deploy well-architected solutions on AWS.',
    skills: ['AWS', 'Cloud Computing', 'Architecture'],
    category: 'Technology',
    slug: 'aws-certified-solutions-architect-associate',
  },
  {
    title: 'Certified Kubernetes Administrator (CKA)',
    issuer: 'The Linux Foundation',
    credentialId: 'CKA-67890',
    credentialUrl: 'https://www.credly.com/badges/67890',
    issueDate: '2023-11-20',
    photoKey: 'cka.png',
    content: 'Demonstrated expertise in managing and administering Kubernetes clusters.',
    skills: ['Kubernetes', 'Docker', 'DevOps'],
    category: 'Technology',
    slug: 'certified-kubernetes-administrator',
  },
  {
    title: 'Project Management Professional (PMP)',
    issuer: 'Project Management Institute',
    credentialId: 'PMP-54321',
    credentialUrl: 'https://www.credly.com/badges/54321',
    issueDate: '2023-05-10',
    expirationDate: '2026-05-10',
    photoKey: 'pmp.png',
    content: 'Globally recognized certification for project management.',
    skills: ['Project Management', 'Agile', 'Scrum'],
    category: 'Business',
    slug: 'project-management-professional',
  },
  {
    title: 'Advanced Spanish Language Certificate',
    issuer: 'Instituto Cervantes',
    credentialId: 'DELE-C1-11223',
    credentialUrl: 'https://examenes.cervantes.es/',
    issueDate: '2022-08-30',
    photoKey: 'dele-c1.png',
    content: 'DELE C1 level certification, demonstrating advanced proficiency in Spanish.',
    skills: ['Spanish'],
    category: 'Languages',
    slug: 'advanced-spanish-language-certificate',
  },
  {
    title: 'First Aid and CPR Certified',
    issuer: 'American Red Cross',
    credentialId: 'ARC-99887',
    credentialUrl: 'https://www.redcross.org/take-a-class/digital-certificate',
    issueDate: '2024-03-01',
    expirationDate: '2026-03-01',
    photoKey: 'first-aid-cpr.png',
    content: 'Certified in providing first aid, CPR, and AED use.',
    skills: ['First Aid', 'CPR'],
    category: 'Health',
    slug: 'first-aid-cpr-certified',
  },
];
