import { Schema } from '../../amplify/data/resource';

type ProjectCreate = Omit<Schema['Projects']['type'], 'id' | 'createdAt' | 'updatedAt'>;

export const projects: ProjectCreate[] = [
  {
    title: 'AI-Powered Portfolio Website',
    description: 'A personal portfolio website built with Next.js, Amplify, and featuring AI-driven content suggestions.',
    place: 'Online',
    projectUrl: 'https://foor.dev',
    githubUrl: 'https://github.com/your-username/your-portfolio',
    demoUrl: 'https://foor.dev',
    skills: ['Next.js', 'React', 'TypeScript', 'AWS Amplify', 'GraphQL'],
    categories: 'Personal',
    photoKey: 'portfolio-main.jpg',
    galleryKeys: ['portfolio-1.jpg', 'portfolio-2.jpg'],
    startDate: '2023-01-01',
    endDate: '2023-06-30',
    status: 'Published',
    featured: true,
    slug: 'ai-powered-portfolio',
    metaDescription: 'My personal portfolio showcasing my projects and skills in web development and AI.',
    tags: ['Next.js', 'Amplify', 'AI'],
  },
  {
    title: 'E-commerce Platform for Local Artisans',
    description: 'A full-stack e-commerce platform for local artisans to sell their products online.',
    place: 'Community Project',
    projectUrl: 'https://artisans-marketplace.com',
    githubUrl: 'https://github.com/your-username/artisans-marketplace',
    skills: ['React', 'Node.js', 'Express', 'MongoDB', 'Stripe'],
    categories: 'Professional',
    photoKey: 'ecommerce-main.jpg',
    startDate: '2022-05-15',
    status: 'Archived',
    featured: false,
    slug: 'ecommerce-artisans',
    metaDescription: 'An online marketplace for local artisans.',
    tags: ['E-commerce', 'React', 'Node.js'],
  },
  {
    title: 'Hackathon: HealthTech App',
    description: 'A mobile app developed during a 48-hour hackathon to connect patients with doctors for virtual consultations.',
    place: 'HealthTech Hackathon 2023',
    demoUrl: 'https://youtube.com/demovideo',
    skills: ['React Native', 'Firebase', 'WebRTC'],
    categories: 'Hackathon',
    photoKey: 'healthtech-app.jpg',
    startDate: '2023-09-22',
    endDate: '2023-09-24',
    status: 'Published',
    featured: true,
    slug: 'hackathon-healthtech-app',
    metaDescription: 'A HealthTech app for virtual medical consultations.',
    tags: ['Hackathon', 'React Native', 'Firebase'],
  },
  {
    title: 'Academic Research: NLP for Sentiment Analysis',
    description: 'Research project on using Natural Language Processing for sentiment analysis on social media data.',
    place: 'University of Technology',
    projectUrl: 'https://university.edu/research/nlp-sentiment-analysis',
    skills: ['Python', 'TensorFlow', 'NLTK', 'Pandas'],
    categories: 'Research',
    photoKey: 'nlp-research.jpg',
    startDate: '2021-09-01',
    endDate: '2022-05-31',
    status: 'Published',
    featured: false,
    slug: 'nlp-sentiment-analysis-research',
    metaDescription: 'University research on NLP for sentiment analysis.',
    tags: ['NLP', 'Python', 'TensorFlow'],
  },
  {
    title: 'Personal Blog on Tech and Development',
    description: 'A personal blog where I write about web development, cloud computing, and software engineering.',
    place: 'Online',
    projectUrl: 'https://mytechblog.com',
    githubUrl: 'https://github.com/your-username/my-tech-blog',
    skills: ['Gatsby', 'React', 'GraphQL', 'Markdown'],
    categories: 'Personal',
    photoKey: 'tech-blog.jpg',
    status: 'Published',
    featured: true,
    slug: 'personal-tech-blog',
    metaDescription: 'A blog about technology and software development.',
    tags: ['Blog', 'Gatsby', 'React'],
  },
];
