
import { Schema } from '../../amplify/data/resource';

type SkillCreate = Omit<Schema['Skills']['type'], 'id' | 'createdAt' | 'updatedAt'>;

export const skills: SkillCreate[] = [
  {
    name: 'Amazon Web Services (AWS)',
    category: 'CLOUD_PLATFORMS',
    type: 'Technical',
    proficiency: 'Expert',
    yearsOfExperience: 5,
    description: 'Extensive experience in designing, deploying, and managing applications on AWS.',
    certifications: ['AWS Certified Solutions Architect - Associate'],
    projects: ['ai-powered-portfolio', 'ecommerce-artisans'],
    iconKey: 'aws-logo.png',
    priority: 1,
    isActive: true,
    isCore: true,
    lastUsed: '2024-06-30',
  },
  {
    name: 'Kubernetes',
    category: 'DEVOPS_TOOLS',
    type: 'Technical',
    proficiency: 'Advanced',
    yearsOfExperience: 3,
    description: 'Proficient in deploying, managing, and scaling containerized applications using Kubernetes.',
    certifications: ['Certified Kubernetes Administrator (CKA)'],
    iconKey: 'kubernetes-logo.png',
    priority: 2,
    isActive: true,
    isCore: true,
    lastUsed: '2024-05-15',
  },
  {
    name: 'Python',
    category: 'PROGRAMMING_LANGUAGES',
    type: 'Technical',
    proficiency: 'Expert',
    yearsOfExperience: 7,
    description: 'Highly skilled in Python for web development, data analysis, and scripting.',
    projects: ['nlp-sentiment-analysis-research'],
    iconKey: 'python-logo.png',
    priority: 3,
    isActive: true,
    isCore: true,
    lastUsed: '2024-06-20',
  },
  {
    name: 'Teamwork',
    category: 'SOFT_SKILLS',
    type: 'Soft',
    proficiency: 'Expert',
    description: 'Proven ability to collaborate effectively in cross-functional teams.',
    examples: ['Led a team of 5 engineers on a critical project', 'Successfully collaborated with product and design teams'],
    achievements: ['Received "Team Player of the Year" award'],
    isActive: true,
    isCore: true,
  },
  {
    name: 'Communication',
    category: 'SOFT_SKILLS',
    type: 'Soft',
    proficiency: 'Advanced',
    description: 'Excellent written and verbal communication skills.',
    examples: ['Presented technical concepts to non-technical stakeholders', 'Wrote clear and concise documentation'],
    isActive: true,
    isCore: false,
  },
];
